############################ default ###########################################
## https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.data
spring:
  application:
    name: "useraccount-ms"
## --------------- >>> logging (begin) <<< -------------------------------------
logging:
  group:
    tomcat: "org.apache.catalina,org.apache.coyote,org.apache.tomcat"
  level:
    com:
      rubensgomes:
        useraccount: "info"
    root: "error"
    tomcat: "warn"
    # spring boot "logging.group.web"
    # org.springframework.core.codec
    # org.springframework.http
    # org.springframework.web
    # org.springframework.boot.actuate.endpoint.web
    # org.springframework.boot.web.servlet.ServletContextInitializerBeans
    web: "warn"
## --------------- >>> logging (end) <<< ---------------------------------------
## server
server:
  error:
    include-message: "always"
  port: 8080
  servlet:
    context-path: "/"
  shutdown: "graceful"